deps-run: &deps-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install --user -r requirements/docs.txt | cat
    pip install --user . | cat
doc-run: &doc-build
  name: Build documentation
  command: make html SPHINXOPTS='-W -q'
  working_directory: doc

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *deps-install
      - run: *doc-build
      - store_artifacts:
          path: doc/build/html
      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/doc/build/html/index.html"

