doc-run: &doc-build
  name: Build documentation
  command: |
    pip install --user -r requirements/docs.txt | cat
    cd doc/ && make html SPHINXOPTS='-W -q'

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *doc-build
      - store_artifacts:
          path: doc/build/html
      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/doc/build/html/index.html"

